server:
  port: 6086
spring:
  application:
    name: resource-processor-service
  config:
    import: "optional:configserver:http://config-server:8888"
  kafka:
    bootstrap-servers: kafka:9092
    streams:
      properties:
        default:
          deserialization:
            exception:
              handler=org:
                apache:
                  kafka:
                    streams:
                      errors: LogAndContinueExceptionHandler
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: false
#  kafka:
#    bootstrap-servers: kafka:9092
#    streams:
#      application-id: kafkaStreams
#      properties:
#        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#        default.value.serde: com.song.resourceprocessor.config.JsonMapSerde
#        default.timestamp.extractor: org.apache.kafka.streams.processor.WallclockTimestampExtractor
#        default:
#          deserialization:
#            exception:
#              handler=org:
#                apache:
#                  kafka:
#                    streams:
#                      errors: LogAndContinueExceptionHandler